// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proto/product/v1/product_service.proto

package productv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Money represents a monetary value with precise decimal arithmetic.
type Money struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Numerator     int64                  `protobuf:"varint,1,opt,name=numerator,proto3" json:"numerator,omitempty"`
	Denominator   int64                  `protobuf:"varint,2,opt,name=denominator,proto3" json:"denominator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Money) Reset() {
	*x = Money{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Money) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Money) ProtoMessage() {}

func (x *Money) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Money.ProtoReflect.Descriptor instead.
func (*Money) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{0}
}

func (x *Money) GetNumerator() int64 {
	if x != nil {
		return x.Numerator
	}
	return 0
}

func (x *Money) GetDenominator() int64 {
	if x != nil {
		return x.Denominator
	}
	return 0
}

// Discount represents a percentage-based discount with a validity period.
type Discount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Percentage    float64                `protobuf:"fixed64,1,opt,name=percentage,proto3" json:"percentage,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Discount) Reset() {
	*x = Discount{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Discount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Discount) ProtoMessage() {}

func (x *Discount) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Discount.ProtoReflect.Descriptor instead.
func (*Discount) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{1}
}

func (x *Discount) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *Discount) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *Discount) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

// Product represents a product in the catalog.
type Product struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description       string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Category          string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	BasePrice         *Money                 `protobuf:"bytes,5,opt,name=base_price,json=basePrice,proto3" json:"base_price,omitempty"`
	EffectivePrice    *Money                 `protobuf:"bytes,6,opt,name=effective_price,json=effectivePrice,proto3" json:"effective_price,omitempty"`
	Discount          *Discount              `protobuf:"bytes,7,opt,name=discount,proto3" json:"discount,omitempty"`
	HasActiveDiscount bool                   `protobuf:"varint,8,opt,name=has_active_discount,json=hasActiveDiscount,proto3" json:"has_active_discount,omitempty"`
	Status            string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{2}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Product) GetBasePrice() *Money {
	if x != nil {
		return x.BasePrice
	}
	return nil
}

func (x *Product) GetEffectivePrice() *Money {
	if x != nil {
		return x.EffectivePrice
	}
	return nil
}

func (x *Product) GetDiscount() *Discount {
	if x != nil {
		return x.Discount
	}
	return nil
}

func (x *Product) GetHasActiveDiscount() bool {
	if x != nil {
		return x.HasActiveDiscount
	}
	return false
}

func (x *Product) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Product) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Product) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// ProductSummary represents a summary of a product for list operations.
type ProductSummary struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category          string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	BasePrice         *Money                 `protobuf:"bytes,4,opt,name=base_price,json=basePrice,proto3" json:"base_price,omitempty"`
	EffectivePrice    *Money                 `protobuf:"bytes,5,opt,name=effective_price,json=effectivePrice,proto3" json:"effective_price,omitempty"`
	HasActiveDiscount bool                   `protobuf:"varint,6,opt,name=has_active_discount,json=hasActiveDiscount,proto3" json:"has_active_discount,omitempty"`
	DiscountPercent   float64                `protobuf:"fixed64,7,opt,name=discount_percent,json=discountPercent,proto3" json:"discount_percent,omitempty"`
	Status            string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ProductSummary) Reset() {
	*x = ProductSummary{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductSummary) ProtoMessage() {}

func (x *ProductSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductSummary.ProtoReflect.Descriptor instead.
func (*ProductSummary) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{3}
}

func (x *ProductSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductSummary) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ProductSummary) GetBasePrice() *Money {
	if x != nil {
		return x.BasePrice
	}
	return nil
}

func (x *ProductSummary) GetEffectivePrice() *Money {
	if x != nil {
		return x.EffectivePrice
	}
	return nil
}

func (x *ProductSummary) GetHasActiveDiscount() bool {
	if x != nil {
		return x.HasActiveDiscount
	}
	return false
}

func (x *ProductSummary) GetDiscountPercent() float64 {
	if x != nil {
		return x.DiscountPercent
	}
	return 0
}

func (x *ProductSummary) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProductSummary) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// CreateProductRequest is the request to create a new product.
type CreateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	BasePrice     *Money                 `protobuf:"bytes,4,opt,name=base_price,json=basePrice,proto3" json:"base_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProductRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateProductRequest) GetBasePrice() *Money {
	if x != nil {
		return x.BasePrice
	}
	return nil
}

// CreateProductReply is the response after creating a product.
type CreateProductReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductReply) Reset() {
	*x = CreateProductReply{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductReply) ProtoMessage() {}

func (x *CreateProductReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductReply.ProtoReflect.Descriptor instead.
func (*CreateProductReply) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{5}
}

func (x *CreateProductReply) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

// UpdateProductRequest is the request to update a product.
type UpdateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductRequest) Reset() {
	*x = UpdateProductRequest{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductRequest) ProtoMessage() {}

func (x *UpdateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateProductRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *UpdateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateProductRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

// UpdateProductReply is the response after updating a product.
type UpdateProductReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductReply) Reset() {
	*x = UpdateProductReply{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductReply) ProtoMessage() {}

func (x *UpdateProductReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductReply.ProtoReflect.Descriptor instead.
func (*UpdateProductReply) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{7}
}

// ActivateProductRequest is the request to activate a product.
type ActivateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateProductRequest) Reset() {
	*x = ActivateProductRequest{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateProductRequest) ProtoMessage() {}

func (x *ActivateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateProductRequest.ProtoReflect.Descriptor instead.
func (*ActivateProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{8}
}

func (x *ActivateProductRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

// ActivateProductReply is the response after activating a product.
type ActivateProductReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateProductReply) Reset() {
	*x = ActivateProductReply{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateProductReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateProductReply) ProtoMessage() {}

func (x *ActivateProductReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateProductReply.ProtoReflect.Descriptor instead.
func (*ActivateProductReply) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{9}
}

// DeactivateProductRequest is the request to deactivate a product.
type DeactivateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateProductRequest) Reset() {
	*x = DeactivateProductRequest{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateProductRequest) ProtoMessage() {}

func (x *DeactivateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateProductRequest.ProtoReflect.Descriptor instead.
func (*DeactivateProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{10}
}

func (x *DeactivateProductRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

// DeactivateProductReply is the response after deactivating a product.
type DeactivateProductReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateProductReply) Reset() {
	*x = DeactivateProductReply{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateProductReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateProductReply) ProtoMessage() {}

func (x *DeactivateProductReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateProductReply.ProtoReflect.Descriptor instead.
func (*DeactivateProductReply) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{11}
}

// ArchiveProductRequest is the request to archive a product.
type ArchiveProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveProductRequest) Reset() {
	*x = ArchiveProductRequest{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveProductRequest) ProtoMessage() {}

func (x *ArchiveProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveProductRequest.ProtoReflect.Descriptor instead.
func (*ArchiveProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{12}
}

func (x *ArchiveProductRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

// ArchiveProductReply is the response after archiving a product.
type ArchiveProductReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveProductReply) Reset() {
	*x = ArchiveProductReply{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveProductReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveProductReply) ProtoMessage() {}

func (x *ArchiveProductReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveProductReply.ProtoReflect.Descriptor instead.
func (*ArchiveProductReply) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{13}
}

// ApplyDiscountRequest is the request to apply a discount to a product.
type ApplyDiscountRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ProductId          string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	DiscountPercentage float64                `protobuf:"fixed64,2,opt,name=discount_percentage,json=discountPercentage,proto3" json:"discount_percentage,omitempty"`
	StartDate          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ApplyDiscountRequest) Reset() {
	*x = ApplyDiscountRequest{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyDiscountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyDiscountRequest) ProtoMessage() {}

func (x *ApplyDiscountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyDiscountRequest.ProtoReflect.Descriptor instead.
func (*ApplyDiscountRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{14}
}

func (x *ApplyDiscountRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ApplyDiscountRequest) GetDiscountPercentage() float64 {
	if x != nil {
		return x.DiscountPercentage
	}
	return 0
}

func (x *ApplyDiscountRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *ApplyDiscountRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

// ApplyDiscountReply is the response after applying a discount.
type ApplyDiscountReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyDiscountReply) Reset() {
	*x = ApplyDiscountReply{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyDiscountReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyDiscountReply) ProtoMessage() {}

func (x *ApplyDiscountReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyDiscountReply.ProtoReflect.Descriptor instead.
func (*ApplyDiscountReply) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{15}
}

// RemoveDiscountRequest is the request to remove a discount from a product.
type RemoveDiscountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveDiscountRequest) Reset() {
	*x = RemoveDiscountRequest{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveDiscountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveDiscountRequest) ProtoMessage() {}

func (x *RemoveDiscountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveDiscountRequest.ProtoReflect.Descriptor instead.
func (*RemoveDiscountRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{16}
}

func (x *RemoveDiscountRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

// RemoveDiscountReply is the response after removing a discount.
type RemoveDiscountReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveDiscountReply) Reset() {
	*x = RemoveDiscountReply{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveDiscountReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveDiscountReply) ProtoMessage() {}

func (x *RemoveDiscountReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveDiscountReply.ProtoReflect.Descriptor instead.
func (*RemoveDiscountReply) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{17}
}

// GetProductRequest is the request to get a product by ID.
type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{18}
}

func (x *GetProductRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

// GetProductReply is the response containing a product.
type GetProductReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductReply) Reset() {
	*x = GetProductReply{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductReply) ProtoMessage() {}

func (x *GetProductReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductReply.ProtoReflect.Descriptor instead.
func (*GetProductReply) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{19}
}

func (x *GetProductReply) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

// ListProductsRequest is the request to list products.
type ListProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ActiveOnly    bool                   `protobuf:"varint,3,opt,name=active_only,json=activeOnly,proto3" json:"active_only,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,5,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsRequest) Reset() {
	*x = ListProductsRequest{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRequest) ProtoMessage() {}

func (x *ListProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRequest.ProtoReflect.Descriptor instead.
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{20}
}

func (x *ListProductsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ListProductsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListProductsRequest) GetActiveOnly() bool {
	if x != nil {
		return x.ActiveOnly
	}
	return false
}

func (x *ListProductsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListProductsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// ListProductsReply is the response containing a list of products.
type ListProductsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*ProductSummary      `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int64                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsReply) Reset() {
	*x = ListProductsReply{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsReply) ProtoMessage() {}

func (x *ListProductsReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsReply.ProtoReflect.Descriptor instead.
func (*ListProductsReply) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{21}
}

func (x *ListProductsReply) GetProducts() []*ProductSummary {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ListProductsReply) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListProductsReply) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_proto_product_v1_product_service_proto protoreflect.FileDescriptor

const file_proto_product_v1_product_service_proto_rawDesc = "" +
	"\n" +
	"&proto/product/v1/product_service.proto\x12\n" +
	"product.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"G\n" +
	"\x05Money\x12\x1c\n" +
	"\tnumerator\x18\x01 \x01(\x03R\tnumerator\x12 \n" +
	"\vdenominator\x18\x02 \x01(\x03R\vdenominator\"\x9c\x01\n" +
	"\bDiscount\x12\x1e\n" +
	"\n" +
	"percentage\x18\x01 \x01(\x01R\n" +
	"percentage\x129\n" +
	"\n" +
	"start_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\"\xc9\x03\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x120\n" +
	"\n" +
	"base_price\x18\x05 \x01(\v2\x11.product.v1.MoneyR\tbasePrice\x12:\n" +
	"\x0feffective_price\x18\x06 \x01(\v2\x11.product.v1.MoneyR\x0eeffectivePrice\x120\n" +
	"\bdiscount\x18\a \x01(\v2\x14.product.v1.DiscountR\bdiscount\x12.\n" +
	"\x13has_active_discount\x18\b \x01(\bR\x11hasActiveDiscount\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xec\x02\n" +
	"\x0eProductSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x120\n" +
	"\n" +
	"base_price\x18\x04 \x01(\v2\x11.product.v1.MoneyR\tbasePrice\x12:\n" +
	"\x0feffective_price\x18\x05 \x01(\v2\x11.product.v1.MoneyR\x0eeffectivePrice\x12.\n" +
	"\x13has_active_discount\x18\x06 \x01(\bR\x11hasActiveDiscount\x12)\n" +
	"\x10discount_percent\x18\a \x01(\x01R\x0fdiscountPercent\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x9a\x01\n" +
	"\x14CreateProductRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x120\n" +
	"\n" +
	"base_price\x18\x04 \x01(\v2\x11.product.v1.MoneyR\tbasePrice\"3\n" +
	"\x12CreateProductReply\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"\x87\x01\n" +
	"\x14UpdateProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\"\x14\n" +
	"\x12UpdateProductReply\"7\n" +
	"\x16ActivateProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"\x16\n" +
	"\x14ActivateProductReply\"9\n" +
	"\x18DeactivateProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"\x18\n" +
	"\x16DeactivateProductReply\"6\n" +
	"\x15ArchiveProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"\x15\n" +
	"\x13ArchiveProductReply\"\xd8\x01\n" +
	"\x14ApplyDiscountRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12/\n" +
	"\x13discount_percentage\x18\x02 \x01(\x01R\x12discountPercentage\x129\n" +
	"\n" +
	"start_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\"\x14\n" +
	"\x12ApplyDiscountReply\"6\n" +
	"\x15RemoveDiscountRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"\x15\n" +
	"\x13RemoveDiscountReply\"2\n" +
	"\x11GetProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"@\n" +
	"\x0fGetProductReply\x12-\n" +
	"\aproduct\x18\x01 \x01(\v2\x13.product.v1.ProductR\aproduct\"\xa6\x01\n" +
	"\x13ListProductsRequest\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1f\n" +
	"\vactive_only\x18\x03 \x01(\bR\n" +
	"activeOnly\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x05 \x01(\tR\tpageToken\"\x94\x01\n" +
	"\x11ListProductsReply\x126\n" +
	"\bproducts\x18\x01 \x03(\v2\x1a.product.v1.ProductSummaryR\bproducts\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x03R\n" +
	"totalCount2\x87\x06\n" +
	"\x0eProductService\x12Q\n" +
	"\rCreateProduct\x12 .product.v1.CreateProductRequest\x1a\x1e.product.v1.CreateProductReply\x12Q\n" +
	"\rUpdateProduct\x12 .product.v1.UpdateProductRequest\x1a\x1e.product.v1.UpdateProductReply\x12W\n" +
	"\x0fActivateProduct\x12\".product.v1.ActivateProductRequest\x1a .product.v1.ActivateProductReply\x12]\n" +
	"\x11DeactivateProduct\x12$.product.v1.DeactivateProductRequest\x1a\".product.v1.DeactivateProductReply\x12T\n" +
	"\x0eArchiveProduct\x12!.product.v1.ArchiveProductRequest\x1a\x1f.product.v1.ArchiveProductReply\x12Q\n" +
	"\rApplyDiscount\x12 .product.v1.ApplyDiscountRequest\x1a\x1e.product.v1.ApplyDiscountReply\x12T\n" +
	"\x0eRemoveDiscount\x12!.product.v1.RemoveDiscountRequest\x1a\x1f.product.v1.RemoveDiscountReply\x12H\n" +
	"\n" +
	"GetProduct\x12\x1d.product.v1.GetProductRequest\x1a\x1b.product.v1.GetProductReply\x12N\n" +
	"\fListProducts\x12\x1f.product.v1.ListProductsRequest\x1a\x1d.product.v1.ListProductsReplyB?Z=github.com/product-catalog-service/proto/product/v1;productv1b\x06proto3"

var (
	file_proto_product_v1_product_service_proto_rawDescOnce sync.Once
	file_proto_product_v1_product_service_proto_rawDescData []byte
)

func file_proto_product_v1_product_service_proto_rawDescGZIP() []byte {
	file_proto_product_v1_product_service_proto_rawDescOnce.Do(func() {
		file_proto_product_v1_product_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_product_v1_product_service_proto_rawDesc), len(file_proto_product_v1_product_service_proto_rawDesc)))
	})
	return file_proto_product_v1_product_service_proto_rawDescData
}

var file_proto_product_v1_product_service_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_proto_product_v1_product_service_proto_goTypes = []any{
	(*Money)(nil),                    // 0: product.v1.Money
	(*Discount)(nil),                 // 1: product.v1.Discount
	(*Product)(nil),                  // 2: product.v1.Product
	(*ProductSummary)(nil),           // 3: product.v1.ProductSummary
	(*CreateProductRequest)(nil),     // 4: product.v1.CreateProductRequest
	(*CreateProductReply)(nil),       // 5: product.v1.CreateProductReply
	(*UpdateProductRequest)(nil),     // 6: product.v1.UpdateProductRequest
	(*UpdateProductReply)(nil),       // 7: product.v1.UpdateProductReply
	(*ActivateProductRequest)(nil),   // 8: product.v1.ActivateProductRequest
	(*ActivateProductReply)(nil),     // 9: product.v1.ActivateProductReply
	(*DeactivateProductRequest)(nil), // 10: product.v1.DeactivateProductRequest
	(*DeactivateProductReply)(nil),   // 11: product.v1.DeactivateProductReply
	(*ArchiveProductRequest)(nil),    // 12: product.v1.ArchiveProductRequest
	(*ArchiveProductReply)(nil),      // 13: product.v1.ArchiveProductReply
	(*ApplyDiscountRequest)(nil),     // 14: product.v1.ApplyDiscountRequest
	(*ApplyDiscountReply)(nil),       // 15: product.v1.ApplyDiscountReply
	(*RemoveDiscountRequest)(nil),    // 16: product.v1.RemoveDiscountRequest
	(*RemoveDiscountReply)(nil),      // 17: product.v1.RemoveDiscountReply
	(*GetProductRequest)(nil),        // 18: product.v1.GetProductRequest
	(*GetProductReply)(nil),          // 19: product.v1.GetProductReply
	(*ListProductsRequest)(nil),      // 20: product.v1.ListProductsRequest
	(*ListProductsReply)(nil),        // 21: product.v1.ListProductsReply
	(*timestamppb.Timestamp)(nil),    // 22: google.protobuf.Timestamp
}
var file_proto_product_v1_product_service_proto_depIdxs = []int32{
	22, // 0: product.v1.Discount.start_date:type_name -> google.protobuf.Timestamp
	22, // 1: product.v1.Discount.end_date:type_name -> google.protobuf.Timestamp
	0,  // 2: product.v1.Product.base_price:type_name -> product.v1.Money
	0,  // 3: product.v1.Product.effective_price:type_name -> product.v1.Money
	1,  // 4: product.v1.Product.discount:type_name -> product.v1.Discount
	22, // 5: product.v1.Product.created_at:type_name -> google.protobuf.Timestamp
	22, // 6: product.v1.Product.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 7: product.v1.ProductSummary.base_price:type_name -> product.v1.Money
	0,  // 8: product.v1.ProductSummary.effective_price:type_name -> product.v1.Money
	22, // 9: product.v1.ProductSummary.created_at:type_name -> google.protobuf.Timestamp
	0,  // 10: product.v1.CreateProductRequest.base_price:type_name -> product.v1.Money
	22, // 11: product.v1.ApplyDiscountRequest.start_date:type_name -> google.protobuf.Timestamp
	22, // 12: product.v1.ApplyDiscountRequest.end_date:type_name -> google.protobuf.Timestamp
	2,  // 13: product.v1.GetProductReply.product:type_name -> product.v1.Product
	3,  // 14: product.v1.ListProductsReply.products:type_name -> product.v1.ProductSummary
	4,  // 15: product.v1.ProductService.CreateProduct:input_type -> product.v1.CreateProductRequest
	6,  // 16: product.v1.ProductService.UpdateProduct:input_type -> product.v1.UpdateProductRequest
	8,  // 17: product.v1.ProductService.ActivateProduct:input_type -> product.v1.ActivateProductRequest
	10, // 18: product.v1.ProductService.DeactivateProduct:input_type -> product.v1.DeactivateProductRequest
	12, // 19: product.v1.ProductService.ArchiveProduct:input_type -> product.v1.ArchiveProductRequest
	14, // 20: product.v1.ProductService.ApplyDiscount:input_type -> product.v1.ApplyDiscountRequest
	16, // 21: product.v1.ProductService.RemoveDiscount:input_type -> product.v1.RemoveDiscountRequest
	18, // 22: product.v1.ProductService.GetProduct:input_type -> product.v1.GetProductRequest
	20, // 23: product.v1.ProductService.ListProducts:input_type -> product.v1.ListProductsRequest
	5,  // 24: product.v1.ProductService.CreateProduct:output_type -> product.v1.CreateProductReply
	7,  // 25: product.v1.ProductService.UpdateProduct:output_type -> product.v1.UpdateProductReply
	9,  // 26: product.v1.ProductService.ActivateProduct:output_type -> product.v1.ActivateProductReply
	11, // 27: product.v1.ProductService.DeactivateProduct:output_type -> product.v1.DeactivateProductReply
	13, // 28: product.v1.ProductService.ArchiveProduct:output_type -> product.v1.ArchiveProductReply
	15, // 29: product.v1.ProductService.ApplyDiscount:output_type -> product.v1.ApplyDiscountReply
	17, // 30: product.v1.ProductService.RemoveDiscount:output_type -> product.v1.RemoveDiscountReply
	19, // 31: product.v1.ProductService.GetProduct:output_type -> product.v1.GetProductReply
	21, // 32: product.v1.ProductService.ListProducts:output_type -> product.v1.ListProductsReply
	24, // [24:33] is the sub-list for method output_type
	15, // [15:24] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_proto_product_v1_product_service_proto_init() }
func file_proto_product_v1_product_service_proto_init() {
	if File_proto_product_v1_product_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_product_v1_product_service_proto_rawDesc), len(file_proto_product_v1_product_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_product_v1_product_service_proto_goTypes,
		DependencyIndexes: file_proto_product_v1_product_service_proto_depIdxs,
		MessageInfos:      file_proto_product_v1_product_service_proto_msgTypes,
	}.Build()
	File_proto_product_v1_product_service_proto = out.File
	file_proto_product_v1_product_service_proto_goTypes = nil
	file_proto_product_v1_product_service_proto_depIdxs = nil
}
